import { Poppins } from 'next/font/google'
import './globals.css'
// import '@fortawesome/fontawesome-free/css/all.min.css' // Removed full FontAwesome CSS import
import ClientLayout from '../components/ClientLayout';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
  title: 'Christiaan Bothma Portfolio',
  description: 'Generated by create.xyz',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://afbvjxbvbszonmmpunei.supabase.co/storage/v1/object/public/chrisp/public/media/favicon.png" type="image/png" />
      </head>
      <body className={poppins.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  )
}